export const GET_ERRORS = 'GET_ERRORS';
export const GET_AND_SAVE_USER_QUERY = 'GET_AND_SAVE_USER_QUERY';
export const GET_AND_SAVE_BOT_REPLY = 'GET_AND_SAVE_BOT_REPLY';
export const SAVE_CHAT = 'SAVE_CHAT';
export const RECIVE_PREVIOUS_CHAT = 'RECIVE_PREVIOUS_CHAT';
export const LOADING_RESULTS = 'LOADING_RESULTS';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNOUT_USER = 'SIGNOUT_USER';
