export const GET_ERRORS = 'GET_ERRORS';
export const GET_AND_SAVE_USER_QUERY = 'GET_AND_SAVE_USER_QUERY';
export const GET_AND_SAVE_BOT_REPLY = 'GET_AND_SAVE_BOT_REPLY';
export const SAVE_CHAT = 'SAVE_CHAT';
export const LOADING_RESULTS = 'LOADING_RESULTS';