export const GET_ERRORS = 'GET_ERRORS';
export const GET_USER_QUERY_FROM_BACKEND = 'GET_USER_QUERY_FROM_BACKEND';
export const GET_EXECUTIVE_ANSWER = 'GET_EXECUTIVE_ANSWER';
export const SAVE_CHAT = 'SAVE_CHAT';
export const LOADING_QUERY = 'LOADING_QUERY';
export const LOGIN_EXECUTIVE = 'LOGIN_EXECUTIVE';
export const LOGOUT_EXECUTIVE = 'SIGNOUT_EXECUTIVE';